### PR TITLE
Added 'currency' and 'typeof' filters

### PR DESCRIPTION
**Pull request by skadimoolam**
Added a new 'currency' filter,
Added a new 'typeof' filter,
Updated demo.html,
Updated polymer-filters.html

### CODE REVIEW

**Comment by skadimoolam** [comment]
Rewrote 'typeof' filter in the way described in the blog piece.

**Comment by addyosmani** [comment]
Can you rebase this against master please?

**Comment by skadimoolam** [comment]
I have rebased all my commits against the master branch and is upto date.

**Comment by skadimoolam** [comment]
I kind of messed up things while rebasing my commits, I'll close this pull and make a brand new one that has far less conflicts.

**Pull request closed without merging**
