### PR TITLE
filter-underscore

### PR DESCRIPTION
**Pull request by hemanth**
```
"UserName" | undersocre 
> user_name
```

### CODE REVIEW

**Comment by addyosmani** [comment]
Did you mean to commit in the implementation too?

**Comment by hemanth** [comment]
@addyosmani Sleep deprived at a hackathon, heh heh missed it, will push that in soon.

**Comment by hemanth** [comment]
@addyosmani Done, thanks! :)

**Comment by addyosmani** [comment]
I came across a situation where this was needed last week so merging. Cheers!

**Comment by hemanth** [comment]
:+1: Thanks.

**Pull request merged**
