### PR TITLE
Remove useless comma, which lead to bower install failed

### PR DESCRIPTION
**Pull request by zycbobby**
The comma lead to bower install failed?

### CODE REVIEW

**Comment by zycbobby** [comment]
#25 #26 seems to be the same problem

**Comment by addyosmani** [comment]
Can we separate the filter-contains and comma fix commits into different PRs? Thanks! And yes..same issue. Sorry!

**Comment by zycbobby** [comment]
Yes, I have re-committed... 

I think maybe not too many people need filter-contains, I can keep it in my branch

**Comment by addyosmani** [comment]
Change LGTM. Thanks!

**Comment by addyosmani** [comment]
I'll be doing some more Polymer issue triage today and will cut out a release of this as part of that.

**Pull request merged**
